version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/employees
    depends_on:
      - mongo
    volumes:
      - ./backend/src:/usr/src/app/src
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend/pages:/usr/src/app/pages
      - ./frontend/components:/usr/src/app/components
      - ./frontend/public:/usr/src/app/public
      - /usr/src/app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
